In [1]:
import pandas as pd

In [41]:
df = pd.read_excel('Titanic.xlsx')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
from config import COLS_DROP
from preprocessing import drop_cols

drop_cols(df, COLS_DROP)

In [47]:
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtype":dtypes, "nunique": nunique}).T

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
dtype,int64,int64,int64,str,str,float64,int64,int64,object,float64,str,str
nunique,891,2,3,891,2,88,7,7,681,248,147,3

In [ ]:
df.info()

In [52]:
cat_cols=["Survived","Pclass","Sex","SibSp","Parch","Embarked"]
df[cat_cols] = df[cat_cols].astype("category")

In [53]:
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtype":dtypes, "nunique": nunique}).T

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
dtype,int64,category,category,str,category,float64,category,category,object,float64,str,category
nunique,891,2,3,891,2,88,7,7,681,248,147,3

In [55]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [59]:
def get_info(df):
    return pd.DataFrame({"dtype": df.dtypes, "nunique": df.nunique()}).T

get_info(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
dtype,int64,category,category,str,category,float64,category,category,object,float64,str,category
nunique,891,2,3,891,2,88,7,7,681,248,147,3

In [62]:
null=df.isnull().sum()
null

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [66]:
r = (null / 891)*100
r

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [ ]:
df = df.dropna(subset=['Embarked'])
df = df.dropna(subset=['Cabin'])

In [70]:
med=df['Age'].median()
df['Age'] = df['Age'].fillna(med,inplace=True)

C:\Users\11\AppData\Local\Temp\ipykernel_40308\526853181.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'] = df['Age'].fillna(med,inplace=True)

In [72]:
df.info()

<class 'pandas.DataFrame'>
Index: 202 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  202 non-null    int64
 1   Survived     202 non-null    category
 2   Pclass       202 non-null    category
 3   Name         202 non-null    str
 4   Sex          202 non-null    category
 5   Age          202 non-null    float64
 6   SibSp        202 non-null    category
 7   Parch        202 non-null    category
 8   Ticket       202 non-null    object
 9   Fare         202 non-null    float64
 10  Cabin        202 non-null    str
 11  Embarked     202 non-null    category
dtypes: category(6), float64(2), int64(1), object(1), str(2)
memory usage: 12.4+ KB